### ISSUE TITLE
error: no matching function for call to ‘translate(glm::vec3) in ArcballCam.cpp

### ISSUE THREAD

**Issue by lmcquellin** [OpenVSP/OpenVSP#125]
Recently attempted a rebuild on Ubuntu 18.04. Built from source a week ago with no issues. Recently pulled from git and the following is returned during make .

```
/home/z600/OpenVSP/repo/src/vsp_graphic/src/ArcballCam.cpp:83:61: error: no matching function for call to ‘translate(glm::vec3)’
     _tMat = glm::translate( glm::vec3(_pan.x, _pan.y, 0.0f) );
```
```
/home/z600/OpenVSP/repo/src/vsp_graphic/src/ArcballCam.cpp: In member function ‘virtual void VSPGraphic::ArcballCam::rotateSphere(float, float, float)’:
/home/z600/OpenVSP/repo/src/vsp_graphic/src/ArcballCam.cpp:146:34: error: ‘yawPitchRoll’ is not a member of ‘glm’
     _rMat = glm::transpose( glm::yawPitchRoll( angleY, angleX, angleZ ) );
```
```
vsp_graphic/CMakeFiles/vsp_graphic.dir/build.make:62: recipe for target 'vsp_graphic/CMakeFiles/vsp_graphic.dir/src/ArcballCam.cpp.o' failed
make[2]: *** [vsp_graphic/CMakeFiles/vsp_graphic.dir/src/ArcballCam.cpp.o] Error 1
CMakeFiles/Makefile2:712: recipe for target 'vsp_graphic/CMakeFiles/vsp_graphic.dir/all' failed
make[1]: *** [vsp_graphic/CMakeFiles/vsp_graphic.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```
Unsure if this is related to an update of glm?
